# Generated by Django 5.1.6 on 2025-02-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('prefix', models.TextField()),
                ('suffix', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
