# Generated by Django 5.1.6 on 2025-02-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
