# Generated by Django 5.1.6 on 2025-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='prefix',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='project',
            name='suffix',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(max_length=250, null=True, unique=True),
        ),
    ]
