# Generated by Django 5.1.6 on 2025-08-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_prefix_project_body_remove_project_suffix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
