# Generated by Django 5.1.6 on 2025-08-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='last_name',
        ),
    ]
