# Generated by Django 5.1.6 on 2025-03-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='image',
            field=models.ImageField(upload_to='assistant/'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='mood',
            field=models.CharField(choices=[('normal', 'normal'), ('happy', 'happy'), ('sad', 'sad')], max_length=10),
        ),
    ]
