# Generated by Django 5.1.6 on 2025-03-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_assistant_image_alter_assistant_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
