# Generated by Django 5.1.6 on 2025-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_assistant_image_alter_assistant_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='image',
            field=models.ImageField(upload_to='assistant/'),
        ),
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
