# Generated by Django 5.1.6 on 2025-03-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_alter_assistant_image_delete_messagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='image',
            field=models.ImageField(upload_to='assistant/'),
        ),
    ]
