# Generated by Django 5.1.6 on 2025-03-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_remove_assistant_public_id_alter_assistant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='public_id',
        ),
    ]
