# Generated by Django 5.1.6 on 2025-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_remove_assistant_public_id_alter_assistant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='public_id',
        ),
        migrations.AlterField(
            model_name='assistant',
            name='image',
            field=models.ImageField(upload_to='assistant/'),
        ),
    ]
