# Generated by Django 5.1.6 on 2025-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_alter_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='image',
            field=models.ImageField(upload_to='assistant/'),
        ),
    ]
