# Generated by Django 5.1.6 on 2025-03-07 12:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_alter_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
