# Generated by Django 5.1.6 on 2025-03-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_remove_assistant_public_id'),
        ('assistant', '0010_alter_assistant_image'),
    ]

    operations = [
    ]
